linux-server-base:
  name: nzbget
  image:
    label: version-v25.0
  port: 6789
  tailscale: true
  resources:
    limits:
      cpu: 1
      memory: 300Mi
    requests:
      cpu: 0.5
      memory: 300Mi
  vpn: true
  extraVolumes:
  - name: downloads
    claim: longhorn-downloads-2-pvc
    path: /downloads
  configSize: 300Mi
