apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  annotations:
    metallb.universe.tf/address-pool: default-pool
    tailscale.com/expose: "true"
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: 80
      targetPort: 8096
