apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  annotations:
    metallb.universe.tf/address-pool: default-pool
    {{- if .Values.tailscale }}
    tailscale.com/expose: "true"
    {{- end }}
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
