---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: lscr.io/linuxserver/{{ .Values.name }}:{{- .Values.image.label }}
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
        - name: config
          mountPath: /config
{{- range $vol := .Values.extraVolumes }}
        - name: {{ $vol.name }}
          mountPath: {{ $vol.path }}
{{- end }}
        resources:
{{ .Values.resources | toYaml | indent 10 }}
{{- if .Values.vpn }}
      - name: gluetun
        image: ghcr.io/qdm12/gluetun:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
          - name: TZ
            value: "Europe/London"
          - name: VPN_SERVICE_PROVIDER
            value: "surfshark"
          - name: VPN_TYPE
            value: "openvpn"
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: surfshark-credentials
                key: user
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: surfshark-credentials
                key: pass
          - name: SERVER_COUNTRIES
            value: "United Kingdom"
          - name: DNS_KEEP_NAMESERVER
            value: "on"  # This can cause DNS leakage :/
{{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-{{ .Values.name }}-config-pvc
{{- range $vol := .Values.extraVolumes }}
        - name: {{ $vol.name }}
          persistentVolumeClaim:
            claimName: {{ $vol.claim }}
{{- end }}
