---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        name: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:{{- .Values.image.label }}
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 6881
          name: torrent-tcp
        - containerPort: 6881
          name: torrent-udp
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        resources:
          limits:
            cpu: 1
            memory: 300Mi
          requests:
            cpu: 0.5
            memory: 300Mi
      - name: gluetun
        image: ghcr.io/qdm12/gluetun:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
          - name: TZ
            value: "Europe/London"
          - name: VPN_SERVICE_PROVIDER
            value: "surfshark"
          - name: VPN_TYPE
            value: "openvpn"
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: surfshark-credentials
                key: user
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: surfshark-credentials
                key: pass
          - name: SERVER_COUNTRIES
            value: "United Kingdom"
          - name: DNS_KEEP_NAMESERVER
            value: "on"  # This can cause DNS leakage :/
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-qbittorrent-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: longhorn-downloads-2-pvc
