linux-server-base:
  name: prowlarr
  image:
    label: 1.35.1
  port: 9696
  tailscale: true
  resources:
    limits:
      cpu: 1
      memory: 300Mi
    requests:
      cpu: 0.5
      memory: 300Mi
  extraVolumes:
