---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-books-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
